@startebnf
CONTINUATION = { BOOK___CHAPTER___SECTION___PAGE___HEADER | BOOK___CHAPTER___SECTION___PAGE___TEXT | BOOK___CHAPTER___SECTION___PAGE___EMPHASIZED | BOOK___CHAPTER___SECTION___PAGE___CODE | BOOK___CHAPTER___SECTION___PAGE___CAPTION_LABEL | BOOK___CHAPTER___SECTION___PAGE___IMAGE | BOOK___CHAPTER___SECTION___PAGE___KEYWORD } ;
@endebnf
